# Generated by Django 2.1.7 on 2019-02-21 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taging_data_title', models.CharField(max_length=200)),
                ('taging_data_detail', models.TextField()),
                ('taging_data_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taging_list_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tagingdata',
            name='taging_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brat.TagingList'),
        ),
    ]
