# Generated by Django 2.1.7 on 2019-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0003_auto_20190223_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagingdata',
            name='author',
        ),
        migrations.AddField(
            model_name='tagingdata',
            name='taging_data_ann',
            field=models.TextField(blank=True),
        ),
    ]
