# Generated by Django 2.1.7 on 2019-02-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0004_auto_20190226_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagingdata',
            name='taging_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
