# Generated by Django 2.1.7 on 2019-03-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0005_tagingdata_taging_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagingdata',
            name='taging_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
