# Generated by Django 2.1.7 on 2019-03-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0006_auto_20190301_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagingdata',
            name='taging_data_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
