# Generated by Django 2.1.7 on 2019-03-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0008_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagingDataRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taging_number', models.IntegerField()),
                ('taging_text', models.CharField(max_length=1024)),
                ('taging_count', models.IntegerField()),
                ('taging_log', models.TextField(blank=True)),
                ('taging_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brat.TagingData')),
            ],
        ),
    ]
