# Generated by Django 2.1.7 on 2019-04-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0011_auto_20190404_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagingdatarate',
            name='taging_tag',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tagingdatarate',
            name='taging_text',
            field=models.TextField(blank=True),
        ),
    ]
