# Generated by Django 2.1.7 on 2019-04-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0012_auto_20190404_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagingdata',
            name='taging_modified',
            field=models.IntegerField(default=0),
        ),
    ]
