# Generated by Django 2.1.7 on 2019-04-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0014_tagingdata_taging_data_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='taging_count',
            field=models.IntegerField(default=0),
        ),
    ]
