# Generated by Django 2.1.7 on 2019-04-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0015_auto_20190409_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagingdatarate',
            name='taging_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
