# Generated by Django 2.1.7 on 2019-04-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0016_auto_20190411_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_taging_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='for_document_taging_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='for_document_taging_count_num',
            field=models.IntegerField(default=0),
        ),
    ]
