# Generated by Django 2.1.7 on 2019-05-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0018_auto_20190416_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagingdata',
            name='taging_data_title',
            field=models.CharField(max_length=200),
        ),
    ]
