# Generated by Django 2.1.7 on 2019-05-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0019_auto_20190511_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestTagingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_taging_time', models.DateTimeField(auto_now_add=True)),
                ('latest_taging_user', models.CharField(max_length=50)),
                ('latest_taging_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tagingdata',
            name='taging_is_full_tag',
            field=models.FloatField(default=0.0),
        ),
    ]
