# Generated by Django 2.1.7 on 2019-05-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brat', '0021_latesttagingdata_latest_taging_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesttagingdata',
            name='latest_taging_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
